# Generated by Django 4.0.2 on 2022-03-02 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=14)),
                ('attempt', models.PositiveIntegerField()),
                ('endpoint', models.CharField(blank=True, max_length=100)),
                ('settings_string', models.CharField(blank=True, max_length=100)),
                ('run_seed', models.CharField(blank=True, max_length=100)),
                ('randomizer_version', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=23)),
                ('level', models.PositiveSmallIntegerField(blank=True)),
                ('hp', models.PositiveSmallIntegerField(blank=True)),
                ('attack', models.PositiveSmallIntegerField(blank=True)),
                ('defense', models.PositiveSmallIntegerField(blank=True)),
                ('sp_attack', models.PositiveSmallIntegerField(blank=True)),
                ('sp_defense', models.PositiveSmallIntegerField(blank=True)),
                ('speed', models.PositiveSmallIntegerField(blank=True)),
                ('ability', models.CharField(blank=True, max_length=30)),
                ('nature', models.CharField(blank=True, max_length=7)),
                ('move_1', models.CharField(blank=True, max_length=20)),
                ('move_2', models.CharField(blank=True, max_length=20)),
                ('move_3', models.CharField(blank=True, max_length=20)),
                ('move_4', models.CharField(blank=True, max_length=20)),
                ('run_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironmon_stats.run')),
            ],
        ),
    ]
